### ISSUE TITLE
How do you edit the code to add openings in the outline and get it to show in the game?

### ISSUE THREAD

**Issue by nmillz** [1owkeyme/UE5-MazeGenerator-Plugin#17]
The Epic Store now auto redirects to FAB and I can't see if you answered how to do that in the original store.
I have added code in the source code that logically should skip adding the location to the OutlineWallCells as well as some new static mesh variables (copied and renamed versions of OutlineWallCells) and those are not visible in the engine. I have tried cleaning and rebuilding the project with no change. Restarting the engine or machine also did not work. Could you provide some info about how to edit the source code and get it available in the game? Thanks!

**Comment by 1owkeyme** [comment]
@nmillz, hi. 

If you have edited source code and want it to appear inside your project to utilize, you have to pull the whole plugin folder into your `YourProject/plugins/` folder and rebuild the whole project. It is considered that your project is a C++ project.

**Comment by nmillz** [comment]
Sorry about the close and re-open, I accidentally pressed the wrong button

**Comment by 1owkeyme** [comment]
> Hi @1owkeyme,
> I edited the code after adding the plugin to my project, so all of the files are already in place. I've tried rebuilding the project multiple times without any changes

This is not how it works, plugin which you have edited is just a source code delivered with engine. Even if you change this file nothing really happens since it is precompiled. You have to either:
1) duplicate my plugin into your project plugins folder, make changes, and re-build project
2) or rebuild the whole engine with your edited in-place plugin.

**Comment by nmillz** [comment]
Can you go into more detail on how to do either of those? I'm not very familiar with plugins and how to essentially make my own.
I've been editing the files that are in "\Program Files\Epic Games\UE_5.3\Engine\Plugins\Marketplace\MazeGenerator\Source\MazeGenerator" which is where the engine took me when I opened up the Maze.cpp class in the content browser.

**Comment by 1owkeyme** [comment]
@nmillz, sure!

1) Create under your project a `plugins` folder like `YourProject/plugins`
2) Disable original MazeGenerator plugin in your project
3) Copy all the plugin from Unreal Source to plugins folder so it looks like `YourProject/plugins/MazeGenerator`
4) Find your .uproject, right-click it, and select generate Visual Studio files, or something like that
5) Go ahead, open a solution(VS, Rider or other), change code, press compile and launch your project after
6) Now you have 'your' version of plugin ready to be enabled in plugins
7) If there is something wrong with naming, I would just rename a maze generator plugin folder to 'MyMazeGenerator'

**Comment by nmillz** [comment]
I got it finally working! It took a lot of tries and eventually I figured out that any reference to the original MazeGenerator needed to be removed for it to work even after renaming. Thank you so much!
